/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/room.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Floor.geometry} material={materials['Material.015']} position={[0, 1.8, 0]} />
      <mesh geometry={nodes.Rug.geometry} material={materials['Material.007']} position={[0.476, 0.439, 0.509]} />
      <mesh geometry={nodes.Couch.geometry} material={materials['Material.019']} position={[0.529, 0.839, -0.969]} scale={1.029}>
        <mesh geometry={nodes.Couch_Legs.geometry} material={materials['Material.020']} position={[-0.011, 0.066, 0.022]} />
        <mesh geometry={nodes.Cushion_Left.geometry} material={materials['Material.021']} position={[-0.308, 0.307, -0.072]} rotation={[1.108, 0, 0]} scale={[0.315, 0.112, 0.292]} />
        <mesh geometry={nodes.Cushion_Right.geometry} material={materials['Material.022']} position={[0.318, 0.307, -0.072]} rotation={[1.108, 0, 0]} scale={[0.315, 0.112, 0.292]} />
        <mesh geometry={nodes.Pillow.geometry} material={materials['Material.025']} position={[-0.483, 0.146, 0.264]} rotation={[0.208, 0.032, -0.262]} />
        <mesh geometry={nodes.Pillow001.geometry} material={materials['Material.032']} position={[0.491, 0.155, 0.293]} rotation={[0.154, 0.096, -0.022]} />
      </mesh>
      <mesh geometry={nodes.Chair.geometry} material={materials['Material.006']} position={[-1.03, 0.839, 0.415]} rotation={[0, Math.PI / 2, 0]} scale={1.029}>
        <mesh geometry={nodes.Couch_Legs001.geometry} material={materials['Material.033']} position={[-0.313, 0.066, 0.022]} />
        <mesh geometry={nodes.Cushion_Left001.geometry} material={materials['Material.012']} position={[-0.308, 0.307, -0.072]} rotation={[1.108, 0, 0]} scale={[0.315, 0.112, 0.292]} />
        <mesh geometry={nodes.Pillow002.geometry} material={materials['Material.013']} position={[-0.475, 0.146, 0.308]} rotation={[0.072, -0.868, 0.114]} />
      </mesh>
      <group position={[0.312, 2.24, -1.506]}>
        <mesh geometry={nodes.Cube007.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials['Material.023']} />
      </group>
      <group position={[0, 1.8, 0]}>
        <mesh geometry={nodes.Cube008.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube008_1.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Hanger.geometry} material={materials['Material.035']} position={[-1.514, 2.792, 0.628]} scale={0.025} />
      <mesh geometry={nodes.Hanger001.geometry} material={materials['Material.036']} position={[-1.514, 2.792, -0.851]} scale={0.025} />
      <mesh geometry={nodes.Rod.geometry} material={materials['Material.037']} position={[-1.407, 2.861, -0.108]} scale={-0.027} />
      <mesh geometry={nodes.Curtain.geometry} material={materials['Material.038']} position={[-1.375, 2.181, 0.245]}>
        <mesh geometry={nodes.Torus.geometry} material={materials['Material.039']} position={[-0.03, 0.681, -0.186]} rotation={[Math.PI / 2, 0, -0.667]} scale={0.654} />
        <mesh geometry={nodes.Torus001.geometry} material={materials['Material.040']} position={[-0.035, 0.681, -0.134]} rotation={[Math.PI / 2, 0, 0.681]} scale={0.654} />
        <mesh geometry={nodes.Torus002.geometry} material={materials['Material.041']} position={[-0.029, 0.68, -0.06]} rotation={[Math.PI / 2, 0, -0.71]} scale={0.654} />
        <mesh geometry={nodes.Torus003.geometry} material={materials['Material.042']} position={[-0.03, 0.681, -0.005]} rotation={[Math.PI / 2, 0, -2.393]} scale={0.654} />
        <mesh geometry={nodes.Torus004.geometry} material={materials['Material.043']} position={[-0.034, 0.68, 0.069]} rotation={[Math.PI / 2, 0, 2.457]} scale={0.654} />
        <mesh geometry={nodes.Torus005.geometry} material={materials['Material.044']} position={[-0.029, 0.682, 0.122]} rotation={[Math.PI / 2, 0, 0.712]} scale={0.654} />
        <mesh geometry={nodes.Torus006.geometry} material={materials['Material.045']} position={[-0.031, 0.68, 0.198]} rotation={[Math.PI / 2, 0, -0.703]} scale={0.654} />
      </mesh>
      <mesh geometry={nodes.Curtain001.geometry} material={materials['Material.004']} position={[-1.375, 2.181, -0.425]}>
        <mesh geometry={nodes.Torus007.geometry} material={materials['Material.046']} position={[-0.03, 0.681, -0.186]} rotation={[Math.PI / 2, 0, -0.667]} scale={0.654} />
        <mesh geometry={nodes.Torus008.geometry} material={materials['Material.047']} position={[-0.035, 0.681, -0.134]} rotation={[Math.PI / 2, 0, 0.681]} scale={0.654} />
        <mesh geometry={nodes.Torus009.geometry} material={materials['Material.048']} position={[-0.029, 0.68, -0.06]} rotation={[Math.PI / 2, 0, -0.71]} scale={0.654} />
        <mesh geometry={nodes.Torus010.geometry} material={materials['Material.049']} position={[-0.03, 0.681, -0.005]} rotation={[Math.PI / 2, 0, -2.393]} scale={0.654} />
        <mesh geometry={nodes.Torus011.geometry} material={materials['Material.050']} position={[-0.034, 0.68, 0.069]} rotation={[Math.PI / 2, 0, 2.457]} scale={0.654} />
        <mesh geometry={nodes.Torus012.geometry} material={materials['Material.051']} position={[-0.029, 0.682, 0.122]} rotation={[Math.PI / 2, 0, 0.712]} scale={0.654} />
        <mesh geometry={nodes.Torus013.geometry} material={materials['Material.052']} position={[-0.031, 0.68, 0.198]} rotation={[Math.PI / 2, 0, -0.703]} scale={0.654} />
      </mesh>
      <mesh geometry={nodes.Lamp.geometry} material={materials['Material.005']} position={[-1.001, 2.7, -1.524]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Sphere.geometry} material={materials['Material.030']} position={[0, 0.278, 0.344]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.104} />
      </mesh>
      <mesh geometry={nodes.Clock.geometry} material={materials['Material.018']} position={[-1.524, 2.826, 1.196]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Cube.geometry} material={materials['Material.053']} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Cube001.geometry} material={materials['Material.054']} rotation={[0, -0.779, Math.PI / 2]} />
        <mesh geometry={nodes.Cube002.geometry} material={materials['Material.055']} rotation={[0, -1.559, 1.571]} />
        <mesh geometry={nodes.Cube003.geometry} material={materials['Material.056']} rotation={[Math.PI, -0.803, -Math.PI / 2]} />
        <mesh geometry={nodes.Cube004.geometry} material={materials['Material.057']} rotation={[Math.PI, -0.024, -Math.PI / 2]} />
        <mesh geometry={nodes.Cube005.geometry} material={materials['Material.058']} rotation={[-Math.PI, 0.755, -Math.PI / 2]} />
        <mesh geometry={nodes.Cube006.geometry} material={materials['Material.059']} rotation={[-Math.PI, 1.535, -Math.PI / 2]} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials['Material.060']} rotation={[0, 0.828, Math.PI / 2]} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials['Material.04']} position={[0, 0.007, 0]} rotation={[0, 0.337, Math.PI / 2]} scale={[0.012, 0.012, 0.043]} />
        <mesh geometry={nodes.Wall.geometry} material={materials.Material} position={[1.026, 1.524, -1.196]} rotation={[0, 0, Math.PI / 2]} />
      </mesh>
      <group position={[0.446, 0.626, 0.492]} scale={[0.569, 0.352, 0.352]}>
        <mesh geometry={nodes.Circle.geometry} material={materials['Material.061']} />
        <mesh geometry={nodes.Circle_1.geometry} material={materials['Material.026']} />
      </group>
      <group position={[0.139, 0.834, 0.575]}>
        <mesh geometry={nodes.Circle001.geometry} material={materials['Material.062']} />
        <mesh geometry={nodes.Circle001_1.geometry} material={materials['Material.063']} />
        <mesh geometry={nodes.Circle001_2.geometry} material={nodes.Circle001_2.material} />
      </group>
      <mesh geometry={nodes.Plate.geometry} material={nodes.Plate.material} position={[0.127, 0.841, 0.562]} scale={0.068} />
      <mesh geometry={nodes.Plate001.geometry} material={nodes.Plate001.material} position={[0.601, 0.842, 0.335]} scale={0.068} />
      <mesh geometry={nodes.Donut.geometry} material={materials['Material.009']} position={[0.611, 0.864, 0.336]} rotation={[0.059, 0.029, 0.057]} scale={0.452}>
        <mesh geometry={nodes.Cube083_1.geometry} material={materials['Material.010']} position={[0.071, 0.038, -0.037]} rotation={[-1.375, -0.355, -2.299]} scale={0.012} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials['Material.028']} position={[0.091, 0.041, -0.016]} rotation={[-1.56, -0.06, -1.556]} scale={[0.006, 0.02, 0.006]} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials['Material.029']} position={[0.075, 0.01, -0.104]} rotation={[-2.679, 0.484, -0.838]} scale={[0.007, 0.016, 0.007]} />
        <mesh geometry={nodes.Cube083_2.geometry} material={materials['Material.010']} position={[0.005, 0.033, -0.116]} rotation={[-2.354, 0.031, -2.222]} scale={0.012} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials['Material.028']} position={[0.032, 0.041, -0.087]} rotation={[-1.513, -0.02, 1.218]} scale={[0.007, 0.023, 0.007]} />
        <mesh geometry={nodes.Cube012_2.geometry} material={materials['Material.029']} position={[0.01, 0.039, -0.107]} rotation={[-1.963, 0.037, -2.579]} scale={[0.007, 0.016, 0.007]} />
        <mesh geometry={nodes.Cube083_3.geometry} material={materials['Material.010']} position={[-0.054, 0.033, -0.103]} rotation={[-2.288, -0.335, -3.017]} scale={0.012} />
        <mesh geometry={nodes.Cube011_3.geometry} material={materials['Material.028']} position={[-0.016, 0.041, -0.091]} rotation={[-1.511, 0.011, -2.589]} scale={[0.006, 0.021, 0.006]} />
        <mesh geometry={nodes.Cube012_3.geometry} material={materials['Material.029']} position={[-0.044, 0.039, -0.098]} rotation={[-1.932, -0.159, 1.763]} scale={[0.006, 0.014, 0.006]} />
        <mesh geometry={nodes.Cube083_4.geometry} material={materials['Material.010']} position={[-0.037, 0.038, -0.071]} rotation={[-1.209, 0.184, 2.517]} scale={0.013} />
        <mesh geometry={nodes.Cube011_4.geometry} material={materials['Material.028']} position={[-0.01, 0.02, -0.058]} rotation={[-0.723, 0.133, -1.302]} scale={[0.007, 0.023, 0.007]} />
        <mesh geometry={nodes.Cube012_4.geometry} material={materials['Material.029']} position={[-0.103, 0.008, -0.074]} rotation={[-2.868, -0.844, -1.559]} scale={[0.006, 0.013, 0.006]} />
        <mesh geometry={nodes.Cube083_5.geometry} material={materials['Material.010']} position={[-0.068, 0.038, -0.043]} rotation={[-1.347, 0.338, 0.951]} scale={0.012} />
        <mesh geometry={nodes.Cube011_5.geometry} material={materials['Material.028']} position={[-0.116, 0.023, -0.042]} rotation={[-2.134, -0.96, 2.228]} scale={[0.007, 0.022, 0.007]} />
        <mesh geometry={nodes.Cube012_5.geometry} material={materials['Material.029']} position={[-0.107, 0.039, -0.01]} rotation={[-1.611, -0.391, -2.956]} scale={[0.007, 0.015, 0.007]} />
        <mesh geometry={nodes.Cube083_6.geometry} material={materials['Material.010']} position={[-0.08, 0.038, -0.003]} rotation={[-1.554, 0.403, -2.838]} scale={0.011} />
        <mesh geometry={nodes.Cube011_6.geometry} material={materials['Material.028']} position={[-0.055, 0.02, -0.02]} rotation={[-1.197, 0.789, -0.091]} scale={[0.007, 0.022, 0.007]} />
        <mesh geometry={nodes.Cube012_6.geometry} material={materials['Material.029']} position={[-0.116, 0.009, 0.052]} rotation={[-0.564, -1.169, -2.255]} scale={[0.007, 0.015, 0.007]} />
        <mesh geometry={nodes.Cube083_7.geometry} material={materials['Material.010']} position={[-0.071, 0.038, 0.037]} rotation={[-1.767, 0.355, -2.865]} scale={0.011} />
        <mesh geometry={nodes.Cube011_7.geometry} material={materials['Material.028']} position={[-0.058, 0.02, 0.01]} rotation={[-1.77, 0.838, -2.366]} scale={[0.006, 0.021, 0.006]} />
        <mesh geometry={nodes.Cube012_7.geometry} material={materials['Material.029']} position={[-0.075, 0.01, 0.104]} rotation={[-0.462, -0.484, -2.147]} scale={[0.006, 0.015, 0.006]} />
        <mesh geometry={nodes.Cube083_8.geometry} material={materials['Material.010']} position={[-0.062, 0.033, 0.098]} rotation={[-0.874, -0.382, -0.374]} scale={0.012} />
        <mesh geometry={nodes.Cube011_8.geometry} material={materials['Material.028']} position={[-0.094, 0.023, 0.079]} rotation={[-0.718, -0.739, -1.194]} scale={[0.006, 0.021, 0.006]} />
        <mesh geometry={nodes.Cube012_8.geometry} material={materials['Material.029']} position={[-0.075, 0.01, 0.104]} rotation={[-0.462, -0.484, 2.906]} scale={[0.007, 0.016, 0.007]} />
        <mesh geometry={nodes.Cube083_9.geometry} material={materials['Material.010']} position={[-0.005, 0.033, 0.116]} rotation={[-0.787, -0.032, -0.029]} scale={0.012} />
        <mesh geometry={nodes.Cube011_9.geometry} material={materials['Material.028']} position={[-0.032, 0.041, 0.087]} rotation={[-1.628, 0.02, 1.451]} scale={[0.006, 0.021, 0.006]} />
        <mesh geometry={nodes.Cube012_9.geometry} material={materials['Material.029']} position={[-0.01, 0.039, 0.107]} rotation={[-1.179, -0.037, -2.544]} scale={[0.006, 0.014, 0.006]} />
        <mesh geometry={nodes.Cube083_10.geometry} material={materials['Material.010']} position={[-0.003, 0.038, 0.08]} rotation={[-1.974, 0.016, 0.813]} scale={0.011} />
        <mesh geometry={nodes.Cube011_10.geometry} material={materials['Material.028']} position={[-0.032, 0.041, 0.087]} rotation={[-1.628, 0.02, 1.997]} scale={[0.006, 0.02, 0.006]} />
        <mesh geometry={nodes.Cube012_10.geometry} material={materials['Material.029']} position={[0.051, 0.01, 0.119]} rotation={[-0.439, 0.43, 2.214]} scale={[0.007, 0.015, 0.007]} />
        <mesh geometry={nodes.Cube083_11.geometry} material={materials['Material.010']} position={[0.035, 0.038, 0.073]} rotation={[-1.943, -0.154, -1.863]} scale={0.012} />
        <mesh geometry={nodes.Cube011_11.geometry} material={materials['Material.028']} position={[0.072, 0.041, 0.06]} rotation={[-1.612, -0.047, -1.071]} scale={[0.007, 0.023, 0.007]} />
        <mesh geometry={nodes.Cube012_11.geometry} material={materials['Material.029']} position={[0.107, 0.039, 0.01]} rotation={[-1.535, 0.391, 2.389]} scale={[0.006, 0.013, 0.006]} />
        <mesh geometry={nodes.Cube083_12.geometry} material={materials['Material.010']} position={[0.08, 0.038, 0.003]} rotation={[-1.586, -0.404, 0.047]} scale={0.012} />
        <mesh geometry={nodes.Cube011_12.geometry} material={materials['Material.028']} position={[0.088, 0.041, 0.031]} rotation={[-1.589, -0.059, 2.383]} scale={[0.006, 0.021, 0.006]} />
        <mesh geometry={nodes.Cube012_12.geometry} material={materials['Material.029']} position={[0.107, 0.039, 0.01]} rotation={[-1.535, 0.391, -0.101]} scale={[0.007, 0.015, 0.007]} />
        <mesh geometry={nodes.Cube083_13.geometry} material={materials['Material.010']} position={[0.051, 0.012, 0.002]} rotation={[-1.603, -0.747, 1.509]} scale={0.012} />
        <mesh geometry={nodes.Cube011_13.geometry} material={materials['Material.028']} position={[0.134, 0.023, -0.041]} rotation={[0.693, -1.199, 0.596]} scale={[0.006, 0.021, 0.006]} />
        <mesh geometry={nodes.Cube012_13.geometry} material={materials['Material.029']} position={[0.129, 0.044, -0.012]} rotation={[1.466, -0.814, 0.158]} scale={[0.006, 0.014, 0.006]} />
        <mesh geometry={nodes.Cube083_14.geometry} material={materials['Material.010']} position={[0.113, 0.047, -0.056]} rotation={[1.225, -0.6, 1.176]} scale={0.012} />
        <mesh geometry={nodes.Cube011_14.geometry} material={materials['Material.028']} position={[0.134, 0.023, -0.041]} rotation={[0.693, -1.199, 1.578]} scale={[0.007, 0.022, 0.007]} />
        <mesh geometry={nodes.Cube012_14.geometry} material={materials['Material.029']} position={[0.129, 0.044, -0.012]} rotation={[1.466, -0.814, -0.967]} scale={[0.007, 0.015, 0.007]} />
        <mesh geometry={nodes.Cube083_15.geometry} material={materials['Material.010']} position={[0.066, 0.053, -0.033]} rotation={[1.738, 0.323, -1.083]} scale={0.011} />
        <mesh geometry={nodes.Cube011_15.geometry} material={materials['Material.028']} position={[0.096, 0.024, -0.103]} rotation={[0.39, -0.714, -2.3]} scale={[0.007, 0.023, 0.007]} />
        <mesh geometry={nodes.Cube012_15.geometry} material={materials['Material.029']} position={[0.065, 0.055, -0.046]} rotation={[1.718, 0.203, -0.798]} scale={[0.007, 0.016, 0.007]} />
        <mesh geometry={nodes.Cube083_16.geometry} material={materials['Material.010']} position={[0.041, 0.053, -0.061]} rotation={[1.877, 0.197, 1.186]} scale={0.012} />
        <mesh geometry={nodes.Cube011_16.geometry} material={materials['Material.028']} position={[0.032, 0.023, -0.137]} rotation={[0.252, -0.224, 0.106]} scale={[0.007, 0.023, 0.007]} />
        <mesh geometry={nodes.Cube012_16.geometry} material={materials['Material.029']} position={[0.054, 0.044, -0.118]} rotation={[0.8, -0.306, -2.42]} scale={[0.006, 0.013, 0.006]} />
        <mesh geometry={nodes.Cube083_17.geometry} material={materials['Material.010']} position={[0.008, 0.047, -0.126]} rotation={[0.89, -0.04, 0.872]} scale={0.011} />
        <mesh geometry={nodes.Cube011_17.geometry} material={materials['Material.028']} position={[0.032, 0.023, -0.137]} rotation={[0.252, -0.224, 1]} scale={[0.006, 0.021, 0.006]} />
        <mesh geometry={nodes.Cube012_17.geometry} material={materials['Material.029']} position={[0.033, 0.055, -0.072]} rotation={[1.799, 0.103, 1.687]} scale={[0.007, 0.015, 0.007]} />
        <mesh geometry={nodes.Cube083_18.geometry} material={materials['Material.010']} position={[0.005, 0.053, -0.073]} rotation={[1.932, 0.022, 0.928]} scale={0.011} />
        <mesh geometry={nodes.Cube011_18.geometry} material={materials['Material.028']} position={[0.012, 0.041, -0.054]} rotation={[2.319, 0.157, 0.795]} scale={[0.007, 0.023, 0.007]} />
        <mesh geometry={nodes.Cube012_18.geometry} material={materials['Material.029']} position={[-0.012, 0.044, -0.129]} rotation={[0.761, 0.068, -0.64]} scale={[0.006, 0.014, 0.006]} />
        <mesh geometry={nodes.Cube083_19.geometry} material={materials['Material.010']} position={[-0.033, 0.053, -0.066]} rotation={[1.898, -0.159, -0.913]} scale={0.013} />
        <mesh geometry={nodes.Cube011_19.geometry} material={materials['Material.028']} position={[-0.103, 0.023, -0.096]} rotation={[0.344, 0.786, 1.136]} scale={[0.007, 0.024, 0.007]} />
        <mesh geometry={nodes.Cube012_19.geometry} material={materials['Material.029']} position={[-0.075, 0.044, -0.106]} rotation={[0.856, 0.439, -0.105]} scale={[0.007, 0.016, 0.007]} />
        <mesh geometry={nodes.Cube083_20.geometry} material={materials['Material.010']} position={[-0.105, 0.047, -0.07]} rotation={[1.148, 0.552, -2.269]} scale={0.013} />
        <mesh geometry={nodes.Cube011_20.geometry} material={materials['Material.028']} position={[-0.078, 0.056, -0.073]} rotation={[1.424, 0.154, -1.371]} scale={[0.007, 0.023, 0.007]} />
        <mesh geometry={nodes.Cube012_20.geometry} material={materials['Material.029']} position={[-0.046, 0.055, -0.065]} rotation={[1.776, -0.144, 2.583]} scale={[0.006, 0.013, 0.006]} />
        <mesh geometry={nodes.Cube083_21.geometry} material={materials['Material.010']} position={[-0.061, 0.053, -0.041]} rotation={[1.777, -0.3, 2.638]} scale={0.012} />
        <mesh geometry={nodes.Cube011_21.geometry} material={materials['Material.028']} position={[-0.078, 0.056, -0.073]} rotation={[1.424, 0.154, -0.829]} scale={[0.007, 0.022, 0.007]} />
        <mesh geometry={nodes.Cube012_21.geometry} material={materials['Material.029']} position={[-0.118, 0.044, -0.054]} rotation={[1.156, 0.721, 2.774]} scale={[0.006, 0.014, 0.006]} />
        <mesh geometry={nodes.Cube083_22.geometry} material={materials['Material.010']} position={[-0.126, 0.047, -0.008]} rotation={[1.522, 0.679, 0.574]} scale={0.012} />
        <mesh geometry={nodes.Cube011_22.geometry} material={materials['Material.028']} position={[-0.104, 0.056, -0.024]} rotation={[1.522, 0.207, -0.022]} scale={[0.007, 0.023, 0.007]} />
        <mesh geometry={nodes.Cube012_22.geometry} material={materials['Material.029']} position={[-0.072, 0.055, -0.033]} rotation={[1.677, -0.227, -1.823]} scale={[0.007, 0.015, 0.007]} />
        <mesh geometry={nodes.Cube083_23.geometry} material={materials['Material.010']} position={[-0.066, 0.053, 0.033]} rotation={[1.404, -0.323, 1.21]} scale={0.012} />
        <mesh geometry={nodes.Cube011_23.geometry} material={materials['Material.028']} position={[-0.102, 0.056, 0.031]} rotation={[1.633, 0.203, 1.751]} scale={[0.007, 0.023, 0.007]} />
        <mesh geometry={nodes.Cube012_23.geometry} material={materials['Material.029']} position={[-0.079, 0.055, 0.008]} rotation={[1.547, -0.249, 0.957]} scale={[0.007, 0.016, 0.007]} />
        <mesh geometry={nodes.Cube083_24.geometry} material={materials['Material.010']} position={[-0.066, 0.053, 0.033]} rotation={[1.404, -0.323, 2.875]} scale={0.011} />
        <mesh geometry={nodes.Cube011_24.geometry} material={materials['Material.028']} position={[-0.102, 0.056, 0.031]} rotation={[1.633, 0.203, 1.992]} scale={[0.007, 0.023, 0.007]} />
        <mesh geometry={nodes.Cube012_24.geometry} material={materials['Material.029']} position={[-0.042, 0.023, 0.004]} rotation={[1.358, -1.146, 0.891]} scale={[0.007, 0.016, 0.007]} />
        <mesh geometry={nodes.Cube083_25.geometry} material={materials['Material.010']} position={[-0.07, 0.047, 0.105]} rotation={[2.164, 0.354, -1.795]} scale={0.012} />
        <mesh geometry={nodes.Cube011_25.geometry} material={materials['Material.028']} position={[-0.096, 0.024, 0.103]} rotation={[2.753, 0.715, 0.677]} scale={[0.007, 0.022, 0.007]} />
        <mesh geometry={nodes.Cube012_25.geometry} material={materials['Material.029']} position={[-0.065, 0.055, 0.046]} rotation={[1.424, -0.203, 2.334]} scale={[0.007, 0.016, 0.007]} />
        <mesh geometry={nodes.Cube083_26.geometry} material={materials['Material.010']} position={[-0.041, 0.053, 0.061]} rotation={[1.265, -0.197, 1.8]} scale={0.013} />
        <mesh geometry={nodes.Cube011_26.geometry} material={materials['Material.028']} position={[-0.073, 0.056, 0.078]} rotation={[1.727, 0.145, -0.679]} scale={[0.006, 0.021, 0.006]} />
        <mesh geometry={nodes.Cube012_26.geometry} material={materials['Material.029']} position={[-0.033, 0.055, 0.072]} rotation={[1.342, -0.103, -1.055]} scale={[0.006, 0.015, 0.006]} />
        <mesh geometry={nodes.Cube083_27.geometry} material={materials['Material.010']} position={[-0.002, 0.019, 0.04]} rotation={[0.309, -0.06, 0.506]} scale={0.011} />
        <mesh geometry={nodes.Cube011_27.geometry} material={materials['Material.028']} position={[-0.012, 0.041, 0.054]} rotation={[0.822, -0.157, 2.532]} scale={[0.006, 0.02, 0.006]} />
        <mesh geometry={nodes.Cube012_27.geometry} material={materials['Material.029']} position={[0.012, 0.044, 0.129]} rotation={[2.381, -0.061, 1.396]} scale={[0.007, 0.015, 0.007]} />
        <mesh geometry={nodes.Cube083_28.geometry} material={materials['Material.010']} position={[0.053, 0.047, 0.116]} rotation={[2.211, -0.238, -1.259]} scale={0.011} />
        <mesh geometry={nodes.Cube011_28.geometry} material={materials['Material.028']} position={[0.03, 0.056, 0.102]} rotation={[1.775, -0.052, -2.061]} scale={[0.007, 0.023, 0.007]} />
        <mesh geometry={nodes.Cube012_28.geometry} material={materials['Material.029']} position={[0.007, 0.055, 0.079]} rotation={[1.321, 0.021, 2.309]} scale={[0.007, 0.015, 0.007]} />
        <mesh geometry={nodes.Cube083_29.geometry} material={materials['Material.010']} position={[0.111, 0.047, 0.064]} rotation={[1.935, -0.585, -1.052]} scale={0.012} />
        <mesh geometry={nodes.Cube011_29.geometry} material={materials['Material.028']} position={[0.115, 0.023, 0.084]} rotation={[2.8, -0.884, -1.441]} scale={[0.007, 0.023, 0.007]} />
        <mesh geometry={nodes.Cube012_29.geometry} material={materials['Material.029']} position={[0.06, 0.055, 0.054]} rotation={[1.396, 0.182, 0.561]} scale={[0.006, 0.013, 0.006]} />
        <mesh geometry={nodes.Cube083_30.geometry} material={materials['Material.010']} position={[0.126, 0.047, 0.008]} rotation={[1.614, -0.679, -2.269]} scale={0.013} />
        <mesh geometry={nodes.Cube011_30.geometry} material={materials['Material.028']} position={[0.137, 0.024, 0.031]} rotation={[2.184, -1.227, 3.027]} scale={[0.006, 0.02, 0.006]} />
        <mesh geometry={nodes.Cube012_30.geometry} material={materials['Material.029']} position={[0.074, 0.055, 0.032]} rotation={[1.481, 0.234, 0.961]} scale={[0.006, 0.013, 0.006]} />
        <mesh geometry={nodes.Cube083_31.geometry} material={materials['Material.010']} position={[0.142, 0.006, 0.01]} rotation={[-2.005, -1.35, 0.082]} scale={0.013} />
        <mesh geometry={nodes.Cube011_31.geometry} material={materials['Material.028']} position={[0.118, -0.012, -0.064]} rotation={[-0.815, -0.059, 2.003]} scale={[0.006, 0.021, 0.006]} />
        <mesh geometry={nodes.Cube012_31.geometry} material={materials['Material.029']} position={[0.113, -0.026, -0.048]} rotation={[-0.337, 1.316, 0.589]} scale={[0.007, 0.016, 0.007]} />
        <mesh geometry={nodes.Cube083_32.geometry} material={materials['Material.010']} position={[0.051, 0.053, 0.054]} rotation={[1.304, 0.249, -2.46]} scale={0.011} />
        <mesh geometry={nodes.Cube011_32.geometry} material={materials['Material.028']} position={[0.067, 0.056, 0.085]} rotation={[1.733, -0.131, 1.487]} scale={[0.006, 0.02, 0.006]} />
        <mesh geometry={nodes.Cube012_32.geometry} material={materials['Material.029']} position={[0.042, 0.055, 0.069]} rotation={[1.355, 0.122, -0.47]} scale={[0.007, 0.015, 0.007]} />
        <mesh geometry={nodes.Cube083_33.geometry} material={materials['Material.010']} position={[0.087, 0.047, 0.093]} rotation={[2.096, -0.45, -1.076]} scale={0.012} />
        <mesh geometry={nodes.Cube011_33.geometry} material={materials['Material.028']} position={[0.088, 0.023, 0.112]} rotation={[2.869, -0.684, -2.727]} scale={[0.007, 0.023, 0.007]} />
        <mesh geometry={nodes.Cube012_33.geometry} material={materials['Material.029']} position={[0.073, 0.039, 0.081]} rotation={[-1.282, 0.262, 0.789]} scale={[0.006, 0.014, 0.006]} />
        <mesh geometry={nodes.Cube083_34.geometry} material={materials['Material.010']} position={[0.081, 0.033, 0.085]} rotation={[-0.946, 0.519, 1.776]} scale={0.013} />
        <mesh geometry={nodes.Torus014.geometry} material={materials['Material.008']} />
      </mesh>
      <group position={[0.401, 0.834, 0.291]}>
        <mesh geometry={nodes.Circle004.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Circle004_1.geometry} material={materials['Material.027']} />
      </group>
      <mesh geometry={nodes.Plate002.geometry} material={nodes.Plate002.material} position={[0.405, 0.841, 0.291]} scale={0.068} />
      <mesh geometry={nodes.Table.geometry} material={materials['Material.016']} position={[-0.909, 1.244, -0.784]}>
        <mesh geometry={nodes.Cube071.geometry} material={materials['Material.064']} position={[0, -0.038, 0]} scale={-0.092} />
        <mesh geometry={nodes.Cylinder086.geometry} material={materials['Material.017']} position={[0, -0.038, 0]} scale={0.929} />
        <mesh geometry={nodes.Cylinder973.geometry} material={materials['Material.001']} position={[-0.005, -0.357, 0.021]} scale={[0.911, 0.294, 0.911]} />
      </mesh>
      <mesh geometry={nodes.Pot.geometry} material={materials['Material.014']} position={[-0.909, 1.375, -0.784]} scale={[0.127, 0.088, 0.127]}>
        <mesh geometry={nodes.Plant.geometry} material={materials['Material.024']} position={[-0.016, 0.597, 0.014]} rotation={[0, 1.054, 0]} scale={[0.182, 0.261, 0.31]} />
      </mesh>
      <mesh geometry={nodes.bg.geometry} material={materials['Material.031']} scale={21.233} />
      <mesh geometry={nodes.Cube083.geometry} material={materials['Material.010']} position={[20.089, 0.768, -6.156]} scale={0.15} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.028']} position={[20.428, 0.774, -6.156]} scale={[0.08, 0.268, 0.08]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.029']} position={[20.69, 0.776, -6.156]} scale={[0.08, 0.181, 0.08]} />
    </group>
  )
}

useGLTF.preload('/room.gltf')
